services:
  express-app:
    image: jqrsound/MOOC_CICD
    port:
      - "8080:8080"
    container_name: express-app
    restart: unless-stopped

  watchtower:
    image: nickfedor/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    restart: unless-stopped
    depends_on:
      -express_app
