services:
  express-app:
    build: ./express-app
    image: express-app:latest
    container_name: express-app
    restart: unless-stopped
    ports:
      - "8080:8080"

  watchtower:
    image: nickfedor/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    restart: unless-stopped
    depends_on:
      - express-app
